project_name: mostcomm
before:
  hooks:
    - go install github.com/cpuguy83/go-md2man/v2@latest
    - go-md2man -in mostcomm.md -out mostcomm.1
builds:
  -
    id: "mostcomm"
    binary: "mostcomm"
    dir: cmd/mostcomm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
archives:
  -
    format_overrides:
      - goos: windows
        format: zip
    files:
      - mostcomm.1
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  -
    vendor: Ubels Software Development
    homepage: https://github.com/arran4/
    maintainer: Arran Ubels <arran@ubels.com.au>
    description: NA
    license: Private
    formats:
      - apk
      - deb
      - rpm
    release: 1
    section: default
    priority: extra
    contents:
      - src: mostcomm.1
        dst: /usr/share/man/man1/mostcomm.1
