version: 2
project_name: mostcomm
before:
  hooks:
    - go install github.com/cpuguy83/go-md2man/v2@latest
    - go-md2man -in mostcomm.md -out mostcomm.1
builds:
  -
    id: "mostcomm"
    binary: "mostcomm"
    dir: cmd/mostcomm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
archives:
  -
    files:
      - mostcomm.1
dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Version }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Version }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: arm64
docker_manifests:
  - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Version }}-arm64"
  - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Version }}-arm64"
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
nfpms:
  -
    vendor: Ubels Software Development
    homepage: https://github.com/arran4/
    maintainer: Arran Ubels <arran@ubels.com.au>
    description: NA
    license: Private
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux
    release: 1
    section: default
    priority: extra
    contents:
      - src: mostcomm.1
        dst: /usr/share/man/man1/mostcomm.1
homebrew_casks:
  -
    repository:
      owner: arran4
      name: homebrew-tap
      branch: "{{.ProjectName}}-{{.Version}}"
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
      pull_request:
        enabled: true
        draft: false
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
