// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"bytes"
	"flag"
	"fmt"
	"io"
	"os"

	"mostcomm"
	"mostcomm/cmd/mostcomm/templates"
)

type Cmd interface {
	Execute(args []string) error
	Usage()
}

type InternalCommand struct {
	Exec      func(args []string) error
	UsageFunc func()
}

func (c *InternalCommand) Execute(args []string) error {
	return c.Exec(args)
}

func (c *InternalCommand) Usage() {
	c.UsageFunc()
}

type UserError struct {
	Err error
	Msg string
}

func (e *UserError) Error() string {
	if e.Err != nil {
		return fmt.Sprintf("%s: %v", e.Msg, e.Err)
	}
	return e.Msg
}

func NewUserError(err error, msg string) *UserError {
	return &UserError{Err: err, Msg: msg}
}

func executeUsage(out io.Writer, templateName string, data interface{}) error {
	return templates.GetTemplates().ExecuteTemplate(out, templateName, data)
}

type RootCmd struct {
	*flag.FlagSet
	Commands          map[string]Cmd
	Description       string
	Version           string
	Commit            string
	Date              string
	dir               string
	fileMask          string
	sort              string
	sortDirect        string
	thresholdPercent  int
	thresholdLines    int
	thresholdMatchMax int
	concurrency       int
	CommandAction     func(c *RootCmd) error
}

func (c *RootCmd) Usage() {
	if err := executeUsage(os.Stderr, "usage.txt", c); err != nil {
		fmt.Fprintf(os.Stderr, "Usage error: %v\n", err)
	}
}

func (c *RootCmd) FlagsString() string {
	var b bytes.Buffer
	c.FlagSet.SetOutput(&b)
	c.FlagSet.PrintDefaults()
	c.FlagSet.SetOutput(os.Stderr)
	return b.String()
}

func (c *RootCmd) UsageRecursive() {
	fmt.Fprintf(os.Stderr, "Usage of %s:\n", os.Args[0])
	c.FlagSet.PrintDefaults()
	fmt.Fprintln(os.Stderr, "  Commands:")
}

func NewRoot(name, version, commit, date string) (*RootCmd, error) {
	c := &RootCmd{
		FlagSet:     flag.NewFlagSet(name, flag.ExitOnError),
		Commands:    make(map[string]Cmd),
		Description: "Detects duplicates in files based on common lines.",
		Version:     version,
		Commit:      commit,
		Date:        date,
	}
	c.FlagSet.Usage = c.Usage

	c.StringVar(&c.dir, "dir", ".", "Directory to scan")

	c.StringVar(&c.fileMask, "mask", "*.txt", "File glob mask to scan, separated")

	c.StringVar(&c.sort, "sort", "none", "Sorting order, algorithms; none, lines, average-coverage")

	c.StringVar(&c.sortDirect, "sort-direction", "ascending", "Sorting direction, algorithms; ascending, descending")

	c.IntVar(&c.thresholdPercent, "percent-threshold", 0, "Minimum required % of the file in common")

	c.IntVar(&c.thresholdLines, "lines-threshold", 0, "Minimum required lines of the file in common")

	c.IntVar(&c.thresholdMatchMax, "match-max-threshold", -1, "Maximum time a match is allowed")

	c.IntVar(&c.concurrency, "concurrency", 0, "Concurrency limit (default 0 = number of CPUs)")

	c.CommandAction = func(c *RootCmd) error {

		mostcomm.Run(c.dir, c.fileMask, c.sort, c.sortDirect, c.thresholdPercent, c.thresholdLines, c.thresholdMatchMax, c.concurrency)
		return nil
	}

	c.Commands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					c.UsageRecursive()
					return nil
				}
			}
			c.Usage()
			return nil
		},
		UsageFunc: c.Usage,
	}
	c.Commands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					c.UsageRecursive()
					return nil
				}
			}
			c.Usage()
			return nil
		},
		UsageFunc: c.Usage,
	}
	c.Commands["version"] = &InternalCommand{
		Exec: func(args []string) error {
			fmt.Printf("Version: %s\nCommit: %s\nDate: %s\n", c.Version, c.Commit, c.Date)
			return nil
		},
		UsageFunc: func() {
			fmt.Fprintf(os.Stderr, "Usage: %s version\n", os.Args[0])
		},
	}
	return c, nil
}

func (c *RootCmd) Execute(args []string) error {
	if err := c.FlagSet.Parse(args); err != nil {
		return NewUserError(err, fmt.Sprintf("flag parse error %s", err.Error()))
	}
	remainingArgs := c.FlagSet.Args()
	if len(remainingArgs) > 0 {
		if cmd, ok := c.Commands[remainingArgs[0]]; ok {
			return cmd.Execute(remainingArgs[1:])
		}
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("mostcomm failed: %w", err)
		}
	}
	return nil
}
